Provide 6.69.1 version
conda-forge/xbyak-feedstock pull request #10
Opened 2023-06-03 10:32 UTC by ilya-lavrenov

Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

2023-06-03 10:32 UTC, ilya-lavrenov commented
@conda-forge-admin, please rerender

2023-06-03 10:44 UTC, ilya-lavrenov commented
@conda-forge-admin, please rerender

2023-06-03 10:56 UTC, ilya-lavrenov commented
@conda-forge-admin, please rerender

2023-06-03 10:58 UTC, ilya-lavrenov commented
@conda-forge-admin, please rerender

2023-06-03 11:14 UTC, ilya-lavrenov commented
@conda-forge-admin, please rerender

2023-06-03 11:37 UTC, ilya-lavrenov commented
@xhochy and @marcelotrevisani 
Could you please review?

2023-06-06 09:35 UTC, xhochy requested changes

2023-06-06 09:35 UTC, xhochy commented on recipe/build.sh
> +cmake --build "$SRC_DIR/build" --config Release --parallel $CPU_COUNT --verbose || exit 1
Why are you adding these `|| exit 1` everywhere?
```suggestion
cmake ${CMAKE_ARGS} -DCMAKE_BUILD_TYPE=Release -S "$SRC_DIR" -B "$SRC_DIR/build"
cmake --build "$SRC_DIR/build" --config Release --parallel $CPU_COUNT --verbose
```

2023-06-06 09:35 UTC, xhochy commented on recipe/build.sh
> +set +ex
```suggestion
set -ex
```

2023-06-09 13:32 UTC, ilya-lavrenov commented
@xhochy could you please have a look once again?

2023-06-10 05:19 UTC, xhochy approved these changes

2023-06-10 05:19 UTC, merged